import { describe, it, expect } from "vitest";
import {
  readFileSync,
  readdirSync,
  statSync,
  existsSync,
} from "node:fs";
import { resolve, join } from "node:path";
import { JSDOM } from "jsdom";

const CHUNKS_DIR = resolve(process.cwd(), "out", "_next", "static", "chunks");
const EN_INDEX_PATH = resolve(process.cwd(), "out", "en", "index.html");
const ES_INDEX_PATH = resolve(process.cwd(), "out", "es", "index.html");

const TOTAL_BUDGET = 307_200; // 300KB in bytes
const CHUNK_BUDGET = 153_600; // 150KB in bytes

function fileSize(path: string): number {
  return statSync(path).size;
}

describe("out/_next/static/chunks/ — bundle budget verification", () => {
  const chunksDir = CHUNKS_DIR;

  if (!existsSync(chunksDir)) {
    describe.skip("Bundle budget — out/ not found, skipping", () => {});
    return;
  }

  it("has at least one JS chunk file", () => {
    const files = readdirSync(chunksDir).filter((f) => f.endsWith(".js"));
    expect(files.length).toBeGreaterThan(0);
  });

  it("total JS bundle size is under 300KB", () => {
    const jsFiles = readdirSync(chunksDir).filter((f) => f.endsWith(".js"));
    const totalBytes = jsFiles.reduce(
      (sum, f) => sum + fileSize(join(chunksDir, f)),
      0
    );
    const totalKB = (totalBytes / 1024).toFixed(1);
    console.log(
      `[Bundle Budget] Total JS: ${totalKB} KB (${jsFiles.length} files)`
    );
    jsFiles.forEach((f) => {
      const kb = (fileSize(join(chunksDir, f)) / 1024).toFixed(1);
      console.log(`  ${f}: ${kb} KB`);
    });
    expect(
      totalBytes,
      `Total JS bundle (${totalKB} KB) exceeds 300KB budget`
    ).toBeLessThanOrEqual(TOTAL_BUDGET);
  });

  it("largest individual chunk is under 150KB", () => {
    const jsFiles = readdirSync(chunksDir).filter((f) => f.endsWith(".js"));
    let largestFile = "";
    let largestSize = 0;
    for (const f of jsFiles) {
      const size = fileSize(join(chunksDir, f));
      if (size > largestSize) {
        largestSize = size;
        largestFile = f;
      }
    }
    const largestKB = (largestSize / 1024).toFixed(1);
    console.log(`[Bundle Budget] Largest chunk: ${largestFile} (${largestKB} KB)`);
    expect(
      largestSize,
      `Largest chunk "${largestFile}" (${largestKB} KB) exceeds 150KB budget`
    ).toBeLessThanOrEqual(CHUNK_BUDGET);
  });
});

function getPreloadLinks(htmlPath: string): HTMLLinkElement[] {
  const html = readFileSync(htmlPath, "utf-8");
  const dom = new JSDOM(html);
  const doc = dom.window.document;
  return Array.from(
    doc.querySelectorAll<HTMLLinkElement>('link[rel="preload"][as="font"]')
  );
}

/** Font preload links generated by next/font/google land in `_next/static/media/` */
function isFontPreload(link: HTMLLinkElement): boolean {
  return (
    link.href.includes("/_next/static/media/") &&
    link.href.endsWith(".woff2")
  );
}

describe("out/en/index.html — font preload verification", () => {
  if (!existsSync(EN_INDEX_PATH)) {
    describe.skip("Font preload — out/en/index.html not found, skipping", () => {});
    return;
  }

  it("has next/font woff2 preload links", () => {
    const allLinks = getPreloadLinks(EN_INDEX_PATH);
    const fontLinks = allLinks.filter(isFontPreload);
    console.log(
      `[Font Preload] Found ${fontLinks.length} next/font preload links in en/index.html`
    );
    fontLinks.forEach((l) => {
      console.log(`  href: ${l.href} type: ${l.type} crossorigin: "${l.crossOrigin}"`);
    });
    expect(
      fontLinks.length,
      "Expected at least one next/font woff2 preload link in en/index.html"
    ).toBeGreaterThan(0);
  });

  it("font preload links have type='font/woff2'", () => {
    const fontLinks = getPreloadLinks(EN_INDEX_PATH).filter(isFontPreload);
    for (const link of fontLinks) {
      expect(link.type).toBe("font/woff2");
    }
  });

  it("font preload links reference valid media paths", () => {
    const fontLinks = getPreloadLinks(EN_INDEX_PATH).filter(isFontPreload);
    for (const link of fontLinks) {
      expect(link.href).toMatch(/^\/_next\/static\/media\/.+\.woff2$/);
    }
  });
});

describe("out/es/index.html — font preload verification", () => {
  if (!existsSync(ES_INDEX_PATH)) {
    describe.skip("Font preload — out/es/index.html not found, skipping", () => {});
    return;
  }

  it("also has next/font woff2 preload links for Spanish locale", () => {
    const fontLinks = getPreloadLinks(ES_INDEX_PATH).filter(isFontPreload);
    expect(
      fontLinks.length,
      "Expected at least one next/font woff2 preload link in es/index.html"
    ).toBeGreaterThan(0);
  });
});
